FROM golang:1.22.6 AS build

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY ./go.mod ./go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/reference/dockerfile/#copy
COPY . ./

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /fortio-commander ./commander/main.go 

FROM therealmitchconnors/fortio-shell:latest

COPY --from=build /fortio-commander /usr/bin/fortio-commander

RUN apk add --no-cache jq